import sys
import bluetooth
import time


class CustomizedBluetoothClient:
    def __init__(self):
        ########################################################################
        # Configure Service Info
        ########################################################################
        self.service_uuid = "0eb3055f-8ede-4485-961a-edf5bded5c70"  # generated by uuid4
        self.service_name = "MyBluetoothService"

        ########################################################################
        # Socket
        ########################################################################
        self.client_sock = None

    def open(self):
        ########################################################################
        # Service Discovery Protocol (SDP): Find Device/Service
        #   Optionally add python args in .vscode/launch.json
        #     (in find_service, using specific bluetooth mac address as args can connect faster than using discover_devices)
        ########################################################################
        addr = None
        if len(sys.argv) < 2:
            print(
                f"No device specified. Searching for {self.service_name} from all nearby bluetooth devices..."
            )
        else:
            addr = sys.argv[1]
            print(f"Searching for {self.service_name} on address {addr}...")

        # Search for the service
        #   Discover devices or search specific address, & only matched uuid will be showed
        #   Reconnect n times every m seconds
        reconnect_times = 3
        sleep_duration = 3
        for reconnect_num in range(1, 1 + reconnect_times):
            service_matches = bluetooth.find_service(
                uuid=self.service_uuid,
                address=addr,
            )
            if len(service_matches) == 0:
                print(
                    f"Re-connecting {self.service_name} services : {reconnect_num} attempt"
                )
                time.sleep(sleep_duration)
            else:
                break

        if len(service_matches) == 0:
            raise RuntimeError(f"Couldn't find the {self.service_name} service.")
        else:
            first_match = service_matches[0]
            port = first_match["port"]
            name = first_match["name"]
            host = first_match["host"]

        ########################################################################
        # Client Socket: Connect to Device/Service
        ########################################################################
        print(f"Connecting to {name} through port {port} on address {host}...")
        self.client_sock = bluetooth.BluetoothSocket(bluetooth.RFCOMM)
        self.client_sock.connect((host, port))
        print("Connected. Type something:")

    def send_loop(self):
        ########################################################################
        # Client Socket: Send Messages
        ########################################################################
        while True:
            data: str = input()
            self.client_sock.send(data)
            if data == "" or data == "exit":
                break

    def close(self):
        ########################################################################
        # Client Socket: Closed
        ########################################################################
        self.client_sock.close()
        print("Closed")


if __name__ == "__main__":
    ########################################################################
    # Bluetooth Connection Lifecycle
    ########################################################################
    bt_client = CustomizedBluetoothClient()
    bt_client.open()
    bt_client.send_loop()
    bt_client.close()
