########################################################################
# Program-specific Service Info
########################################################################
SERVICE_UUID = "0eb3055f-8ede-4485-961a-edf5bded5c70"  # Generated by uuid4
SERVICE_NAME = "MyBluetoothService"

########################################################################
# Reconnect if Discover Fails
########################################################################
RECONNECT_TIMES = 3
RECONNECT_INTERVAL = 3

########################################################################
# Solve Bluetooth Buffer Size Constraint by Chunk-based Communication
########################################################################
COMM_BUFFER_SIZE = 1024
MSG_MAX_SIZE = 980
SPLIT_SIGN = "|||S|P|L|I|T|||"
WAIT_NEXT_CHUNK = 0.1  # Too high decrease performance, too low may not received (multi-thread may help, but still)
