import bluetooth


class CustomizedBluetoothServer:
    def __init__(self):
        ########################################################################
        # Configure Service Info
        ########################################################################
        self.service_uuid = "0eb3055f-8ede-4485-961a-edf5bded5c70"  # generated by uuid4
        self.service_name = "MyBluetoothService"

        ########################################################################
        # Socket
        ########################################################################
        self.server_sock = None
        self.client_sock = None

    def open(self):
        ########################################################################
        # Server Socket: Open Advertise Service
        ########################################################################
        self.server_sock = bluetooth.BluetoothSocket(bluetooth.RFCOMM)
        self.server_sock.bind(("", bluetooth.PORT_ANY))
        self.server_sock.listen(1)
        service_port = self.server_sock.getsockname()[1]

        bluetooth.advertise_service(
            self.server_sock,
            self.service_name,
            service_id=self.service_uuid,
            service_classes=[self.service_uuid, bluetooth.SERIAL_PORT_CLASS],
            profiles=[bluetooth.SERIAL_PORT_PROFILE],
            # protocols=[bluetooth.OBEX_UUID]
        )

        ########################################################################
        # Client Socket: Created through Server Socket
        ########################################################################
        print(f"Waiting for connection on RFCOMM port {service_port}")
        self.client_sock, client_info = self.server_sock.accept()
        print(f"Accepted connection from {client_info}")

    def recv_loop(self):
        ########################################################################
        # Client Socket: Receive Messages
        ########################################################################
        try:
            while True:
                data: bytes = self.client_sock.recv(1024)
                print(f"Received: {data.decode('UTF-8')}")
                if not data or data == "exit":
                    break
        except OSError:
            print(f"Exit Loop")

    def close(self):
        ########################################################################
        # Client Socket: Closed
        ########################################################################
        self.client_sock.close()
        self.server_sock.close()
        print("Closed")


if __name__ == "__main__":
    ########################################################################
    # Bluetooth Service Lifecycle
    ########################################################################
    bt_server = CustomizedBluetoothServer()
    bt_server.open()
    bt_server.recv_loop()
    bt_server.close()
